# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20170928_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendo', to='exam.User'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='exam.User'),
        ),
    ]
